# -*- coding: utf-8 -*-
"""clase 3 apuntes- operadores lógicos, listas y métodos, validaciones de datos-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nllFvF1RxlU8ZbaKBUpOQq3EBycAuvuU
"""

# if temperatura >= 20  and temperatura <= 80
# and or not
#combustible
#seguridad
#permiso
combustible = True
seguridad = True
permiso = False
if combustible and permiso and seguridad:
  print("Puede volar")
else:
  print("No puede volar")
if combustible or permiso or seguridad:
  print("Revise sus parametros")
if not combustible:
  print("No puede volar")

#diseñar regla de desición
#  muestra colocada
#sensor conectado
#temperatura adecuada
#presion adecuada
#ausencia de alarmas

#las listas no solo guardan datos, la realidad produce conjunto de datos

#. append() añade, .sort ordena, .sorted nos devuelve una nueva lista

validas = [1, 2, 3, 20, 80]
temperatura_valida = 1000
if  temperatura_valida:
  validas.append(temperatura_valida)
validas.sort()
print(validas)

validas = [1, 2, 3, 20, 80]
temperatura_valida = 100
if  temperatura_valida:
  validas.append(temperatura_valida)
lista_ordenada = sorted(validas)
print(validas)


# .pop() - phyton cuenta iniciando desde el cero
validas.pop()
validas.remove(20)
print(validas)
#.remove quita los objetos directamente


#.insert inserta una variable en algun lugar que elijamos
validas.insert(2,20)
print(validas)


#.copy copia la lista
validas.copy()

#reverse invierte los datos
validas.reverse()
print(validas)
#len
longitud = len(validas)
print(longitud)
#clean sirve para vaciar la lista
validas.clear()
print(validas)

# try --> intenta medir
#excep ---> manejar el problema
#finally ---> cierre del procedimiento
# guardamos resultados
#guardamos archivos
#apagamos equipos
#liberar recursos

try:
  #intenta esto
except TypeError:
  ....
finally:
  #se ejecuta siempre

print("Un objeto de masa m se encuentra sobre una superficie plana, sin friccion")

lista_fuerzas = [30,20,10,90,100,2]
print("Lista de fuerzas:", lista_fuerzas)
sumatoria_de_fuerzas = 242
suma = float(input("Coloca la fuerza total:"))
if suma == 242:
  lista_fuerzas.clear()
  if suma == sumatoria_de_fuerzas:
    lista_fuerzas.append(sumatoria_de_fuerzas)
  print("La sumatoria de fuerzas es correcta:", lista_fuerzas )
else:

  print("La sumatoria de fuerzas es incorrecta")