# -*- coding: utf-8 -*-
"""primera clase :p.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-zRzBYzkCkSVUNqrhE7l0ciNDOfpX2s
"""

masa = 3
velocidad = 10
energia = 0.5 * masa * velocidad**2
print(energia)



#funcion
def energia_cinetica(masa, velocidad):
  return 0.5 * masa * velocidad
resultado = energia_cinetica(2,10)
print(resultado)

#momento lineal
m = 30
v = 10
momento_lineal = m*v
print("El momento lineal es igual a:", momento_lineal)

#momento lineal
def momento_lineal(masa,velocidad):
  return masa * velocidad
resultado = momento_lineal(20,10.5)
print(resultado , ": kg*m/s")

#imput nos permite ver de forma mas visual, es decir pedir datos al usuario

PI = 3.1416
radio = float(input("Ingresa el radio : "))
area = (PI) * (radio**2)
print("El area del circulo es : %.4f" % area)

#concatenar
a = 10
b = "30"
print(a + int(b))
print (b + str(a))

# falso verdadero
altura = 100
altura == 100
print(altura > 0)
print(altura == 0)
print(altura < 0)

#condiciones if condicion: hacer_algo --- propisiciones logicas
momento_lineal = float(input("Ingresa la cantidad de momento: "))
if momento_lineal > 0:
  print("La direccion de movimiento es hacia la derecha")
else:
  print("La direccion de movimiento es hacia la izquierda")

#elif va poniendo mas condiciones dentro del bloque principal
y0 = 0
v0 = 20
g = 9.81
t = 4

altura = y0 + v0*t - 0.5*g*t**2
print("Altura  ", altura)
if altura > 0:
  print("El objeto esta en el aire")
if t < 4:
  print("Como el tiempo es menor a 4, el objeto esta por encima del eje de referencia")

elif altura < 0:
  print("El objeto se encuentra en el eje negativo del eje de referencia")
elif altura == 0:
  print("El objeto esta en el suelo")

#Es necesario checar los errores, a pesar de que la celda de codigo sea diferente, el error se seguira arrastrando