# -*- coding: utf-8 -*-
"""Repaso_segunda_clase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEozkDg8CLEH3GHOeXogK201xJWchRht

Logica, condiciones y bucles

**Operadores logicos**
"""

# los boleanos son or, not, and
a =  True
b = False
resultado_uno = a or b
resultado_dos = a and b
resultado_tres = not a
print(resultado_uno)
print(resultado_dos)
print(resultado_tres)

#la funcion bool rebota si un valor es verdadero o falso
numero = 10
texto = "Hey"
vacio = ""
bool_numero = bool(numero)
bool_texto = bool(texto)
bool_vacio = bool(vacio)
print(bool_numero)
print(bool_texto)
print(bool_vacio)

#ciclos while y for
#el ciclo while se repite hasta que se cumpla y for recorre una lista
contrasena = "Copo"
contador = 0
while True:
  contrasena_input = input("ingrese la contraseña: ")
  contador += 1
  if contador ==3:
    print("Has agotado tus intentos")
    break
  elif contador == 2:
    print("Tienes un intento mas")

  elif contrasena_input == "Copo":
    print("Contraseña correcta")
    break
  else:
      print("Contraseña incorrecta", "Lleva ", contador, " intentos")

for numero in range(1,5):
  if numero %2 == 0:
    print("El numero", numero, "es par")
  else:
    print("El numero", numero, "es impar")
#

"""Reto 7 — Clasificador de riesgo de experimento

Un experimento tiene tres factores de riesgo:

temperatura;
presión;
nivel de vibración.

El programa debe clasificar el riesgo como:

bajo;
medio;
alto;
crítico.

Reglas:

Si temperatura > 90 o presión > 120, el riesgo es crítico.
Si vibración > 70 y temperatura > 70, el riesgo es alto.
Si solo uno de los valores está moderadamente elevado, el riesgo es medio.
Si todo está dentro de rango, el riesgo es bajo.

Rangos normales:

temperatura <= 70
presión <= 100
vibración <= 50
Lo que debe pensar el alumno
¿Cuántas variables necesito?
¿Qué valores son constantes?
¿Qué condición debe revisarse primero?
¿Qué pasa si varias condiciones se cumplen al mismo tiempo?
¿Por qué el orden de los if importa?
Restr…
[9:11 p.m., 17/6/2026] Babatha: Reto 4 — Calibración de un instrumento

Un instrumento está calibrado cuando una lectura cae dentro del rango permitido.

El rango permitido es de 9.5 a 10.5.

El programa debe pedir lecturas al usuario hasta que una lectura esté dentro del rango.

Cuando la lectura sea correcta, debe terminar y mostrar:

Instrumento calibrado.

Si la lectura está por debajo del rango, debe decir:

Lectura baja, ajusta hacia arriba.

Si está por encima, debe decir:

Lectura alta, ajusta hacia abajo.
Lo que debe pensar el alumno
¿Conviene pedir datos al usuario?
¿Qué tipo de dato devuelve input()?
¿Cómo convierto ese dato a número?
¿Conviene while o while True?
¿Cuándo se detiene el ciclo?
Restricciones

Debe usar while o while True.

Debe terminar solo cuando la lectura sea válida.

Pista

Cuando no sabes cuántas veces se repetirá algo, while suele ser mejor que for.

Esaú Aguilar
7:49 PM
Emma Ej. 4

Reto 3 — Detector de mediciones sospechosas

Un sensor registra varias mediciones. Algunas pueden ser válidas y otras sospechosas.

Una medición es sospechosa si:

es negativa;
es mayor a 100;
es exactamente igual a la medición anterior.

El programa debe revisar una lista de mediciones y mostrar cuáles son válidas y cuáles son sospechosas.

Además, debe contar:

cuántas mediciones válidas hubo;
cuántas sospechosas hubo.

Ejemplo de lista:

mediciones = [12, 15, 15, -3, 40, 105, 41]


Preguntas de apoyo

¿Qué tipo de dato conviene para guardar varias mediciones?
¿Necesito recordar la medición anterior?
¿Qué condiciones hacen que una medición sea sospechosa?
¿Cómo cuento válidas y sospechosas?
¿Qué pasa con la primera medición si no hay medición anterior?
Restricciones

Debe usar un bucle.

Debe detectar repetición con respecto a la medición anterior.

Pista

Necesitas una variable que recuerde “lo anterior”.

Esaú Aguilar
8:09 PM
* TABATHA *

Reto 5 — Caja negra de una misión

Una misión recibe comandos en secuencia.

Los comandos posibles son:

INICIAR
MEDIR
GUARDAR
ERROR
DETENER

El programa debe recorrer una lista de comandos y procesarlos.

Reglas:

Si el comando es INICIAR, mostrar “Misión iniciada”.
Si es MEDIR, aumentar en 1 el contador de mediciones.
Si es GUARDAR, mostrar cuántas mediciones se han guardado.
Si es ERROR, aumentar en 1 el contador de errores.
Si hay 2 errores, la misión se aborta.
Si aparece DETENER, la misión termina.

Ejemplo:

comandos = ["INICIAR", "MEDIR", "MEDIR", "ERROR", "GUARDAR", "ERROR", "MEDIR"]
Lo que debe pensar el alumno
¿Qué datos son texto?
¿Qué contadores necesito?
¿Qué condiciones evalúo?
¿Uso for o while?
¿Cómo corto el proceso antes de terminar toda la lista?
¿Dónde uso break?
Restricciones

Debe usar un bucle.

Debe detener la misión si hay 2 errores o si aparece DETENER.

Pista

Necesitas contar errores y revisar después de cada comando si ya se llegó al límite.

Esaú Aguilar
8:13 PM
* XAVIER *

Reto 8 — Menú interactivo de laboratorio

Crear un menú que se repita hasta que el usuario decida salir.

El menú debe mostrar:

1. Registrar muestra
2. Ver contador de muestras
3. Reiniciar contador
4. Salir

Reglas:

Si el usuario elige 1, aumenta el contador de muestras.
Si elige 2, muestra cuántas muestras se han registrado.
Si elige 3, reinicia el contador a cero.
Si elige 4, termina el programa.
Si escribe otra opción, muestra “Opción inválida”.
Lo que debe pensar el alumno
¿Por qué aquí conviene while True?
¿Qué variable debe conservarse durante todo el programa?
¿Qué opciones son texto y cuáles números?
¿Dónde uso break?
¿Qué pasa si el usuario escribe algo que no esperaba?
Restricciones

Debe usar while True.

Debe usar break para salir.

No debe terminar después de una sola opción.

Pista

Un menú normalmente vive dentro de un ciclo infinito controlado por una opción de salida.
"""

#ejercicio calibracion de energia
medida_temperatura = float((input("temperatura = ")))
medida_vibracion = float((input("vibración = ")))
medida_presion = float((input("presión = ")))

if medida_temperatura > 90 and medida_presion < 100 and medida_vibracion < 50:
  print("El riesgo es medio")
elif medida_temperatura < 70 and medida_presion > 120 and medida_vibracion < 50:
  print("El riesgo es medio")
elif medida_temperatura < 70 and medida_presion < 100 and medida_vibracion > 70:
  print("El riesgo es medio")
elif medida_temperatura > 90 or medida_presion > 120:
  print("El riesgo es critico")
elif medida_vibracion > 70 and medida_temperatura > 70:
  print("El riesgo es alto")
else:
  medida_temperatura <= 70 and medida_presion <= 100 and medida_vibracion <= 50
  print("Riesgo bajo")

"""Babatha: Reto 4 — Calibración de un instrumento

Un instrumento está calibrado cuando una lectura cae dentro del rango permitido.

El rango permitido es de 9.5 a 10.5.

El programa debe pedir lecturas al usuario hasta que una lectura esté dentro del rango.

Cuando la lectura sea correcta, debe terminar y mostrar:

Instrumento calibrado.

Si la lectura está por debajo del rango, debe decir:

Lectura baja, ajusta hacia arriba.

Si está por encima, debe decir:

Lectura alta, ajusta hacia abajo.
Lo que debe pensar el alumno
¿Conviene pedir datos al usuario?
¿Qué tipo de dato devuelve input()?
¿Cómo convierto ese dato a número?
¿Conviene while o while True?
¿Cuándo se detiene el ciclo?
Restricciones

Debe usar while o while True.

Debe terminar solo cuando la lectura sea válida.

Pista

Cuando no sabes cuántas veces se repetirá algo, while suele ser mejor que for.
"""

rango_calibrado_inferior = 9.5
rango_calibrado_superior = 10.5
solicitar_rango = float(input("Coloca el rango: "))
while True:
  if solicitar_rango < 9.5:
    print("Lectura baja, ajusta hacia arriba")
    break
  elif solicitar_rango > 10.5:
    print("Lectura alta, ajusta hacia abajo")
    break
  else:
      print("Instrumento calibrado")
      break

"""TABATHA *
Reto 5 — Caja negra de una misión

Una misión recibe comandos en secuencia.

Los comandos posibles son:

INICIAR MEDIR GUARDAR ERROR DETENER

El programa debe recorrer una lista de comandos y procesarlos.

Reglas:

Si el comando es INICIAR, mostrar “Misión iniciada”. Si es MEDIR, aumentar en 1 el contador de mediciones. Si es GUARDAR, mostrar cuántas mediciones se han guardado. Si es ERROR, aumentar en 1 el contador de errores. Si hay 2 errores, la misión se aborta. Si aparece DETENER, la misión termina.

Ejemplo:

comandos = ["INICIAR", "MEDIR", "MEDIR", "ERROR", "GUARDAR", "ERROR", "MEDIR"] Lo que debe pensar el alumno ¿Qué datos son texto? ¿Qué contadores necesito? ¿Qué condiciones evalúo? ¿Uso for o while? ¿Cómo corto el proceso antes de terminar toda la lista? ¿Dónde uso break? Restricciones

Debe usar un bucle.

Debe detener la misión si hay 2 errores o si aparece DETENER.

Pista

Necesitas contar errores y revisar después de cada comando si ya se llegó al límite.
"""

#EJERCICIO CAJA NEGRA DE UNA MISIÓN
comandos = ["INICIAR", "MEDIR", "MEDIR", "ERROR", "GUARDAR", "ERROR", "MEDIR"]
contador = 0
errores = 0
mediciones = 0

for comando in comandos:
  colocar_comando = input("Coloque el comando: ")
  if colocar_comando == "INICIAR":
    print("Mision iniciada")
  elif colocar_comando == "MEDIR":
    mediciones += 1
    print("se registraron", mediciones, "mediciones")
    print("Medicion")

  elif colocar_comando == "ERROR":
    errores += 1
    print("se registraron: ", errores, " errores")
    print("Error")
    if errores == 2:
      print("La mision se aborta")
      break


  elif colocar_comando == "GUARDAR":

    print("se tienen guardadas ", mediciones, "mediciones")
    print("Guardado")

  elif colocar_comando == "DETENER":
    print("Detenido")
    break
  elif colocar_comando != comandos:
    print("Opcion invalida")
    break

"""XAVIER *
Reto 8 — Menú interactivo de laboratorio

Crear un menú que se repita hasta que el usuario decida salir.

El menú debe mostrar:

Registrar muestra
Ver contador de muestras
Reiniciar contador
Salir
Reglas:

Si el usuario elige 1, aumenta el contador de muestras. Si elige 2, muestra cuántas muestras se han registrado. Si elige 3, reinicia el contador a cero. Si elige 4, termina el programa. Si escribe otra opción, muestra “Opción inválida”. Lo que debe pensar el alumno ¿Por qué aquí conviene while True? ¿Qué variable debe conservarse durante todo el programa? ¿Qué opciones son texto y cuáles números? ¿Dónde uso break? ¿Qué pasa si el usuario escribe algo que no esperaba? Restricciones

Debe usar while True.

Debe usar break para salir.

No debe terminar después de una sola opción.

Pista

Un menú normalmente vive dentro de un ciclo infinito controlado por una opción de salida.
"""

menu = [1 , 2 , 3, 4]

muestras = 0
print(menu)
usuario = int(input(">>>> Elija una opción del menu: "))
while True:
    if usuario == 1:
      muestras += 1
      print("Se añadio una muestra")
      print(menu)
      usuario = int(input(">>>> Elija una opción del menu: "))

    elif usuario == 2:
      print("Este es el número de muestras registradas: ", muestras)
      print(menu)
      usuario = int(input(">>>> Elija una opción del menu: "))
    elif usuario == 3:
      muestras =  0
      print("EL número de muestras se ha eliminado = ", muestras)
      1
      print(menu)
      usuario = int(input(">>>> Elija una opción del menu: "))
    elif usuario == 4:
      print("Gracias por usar el programa")
      break
    else:
      usuario != menu

      print("Opcion invalida")
      break